feign:
  client:
    config:
      feignName:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: full

hystrix:
 command:
   default:
     execution:
        timeout:
          enabled: false
